<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "advert_status".
 *
 * @property integer $id
 * @property string $name
 * @property string $slug
 *
 * @property \common\models\Advert[] $adverts
 * @property string $aliasModel
 */
abstract class AdvertStatus extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'advert_status';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'slug'], 'required'],
            [['name', 'slug'], 'string', 'max' => 255],
            [['slug'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'slug' => Yii::t('app', 'Slug'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdverts()
    {
        return $this->hasMany(\common\models\Advert::className(), ['status_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\AdvertStatusQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\AdvertStatusQuery(get_called_class());
    }


}
