<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "advert".
 *
 * @property integer $id
 * @property boolean $active
 * @property integer $status_id
 * @property integer $user_id
 * @property string $name
 * @property string $description
 * @property integer $photo_file_id
 * @property string $url
 * @property string $date
 *
 * @property \common\models\AdvertStatus $status
 * @property \common\models\File $photoFile
 * @property \common\models\User $user
 * @property string $aliasModel
 */
abstract class Advert extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'advert';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['active'], 'boolean'],
            [['status_id', 'name'], 'required'],
            [['status_id', 'user_id', 'photo_file_id'], 'integer'],
            [['description'], 'string'],
            [['date'], 'safe'],
            [['name', 'url'], 'string', 'max' => 255],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => AdvertStatus::className(), 'targetAttribute' => ['status_id' => 'id']],
            [['photo_file_id'], 'exist', 'skipOnError' => true, 'targetClass' => File::className(), 'targetAttribute' => ['photo_file_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'active' => Yii::t('app', 'Active'),
            'status_id' => Yii::t('app', 'Status ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'name' => Yii::t('app', 'Name'),
            'description' => Yii::t('app', 'Description'),
            'photo_file_id' => Yii::t('app', 'Photo File ID'),
            'url' => Yii::t('app', 'Url'),
            'date' => Yii::t('app', 'Date'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(\common\models\AdvertStatus::className(), ['id' => 'status_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPhotoFile()
    {
        return $this->hasOne(\common\models\File::className(), ['id' => 'photo_file_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'user_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\AdvertQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\AdvertQuery(get_called_class());
    }


}
