<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "competition_prize".
 *
 * @property integer $id
 * @property integer $competition_id
 * @property string $name
 * @property string $url
 * @property integer $position
 *
 * @property \common\models\Competition $competition
 * @property \common\models\CompetitionWinner[] $competitionWinners
 * @property \common\models\CompetitionUser[] $users
 * @property string $aliasModel
 */
abstract class CompetitionPrize extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'competition_prize';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['competition_id', 'name', 'position'], 'required'],
            [['competition_id', 'position'], 'integer'],
            [['name', 'url'], 'string', 'max' => 255],
            [['competition_id'], 'exist', 'skipOnError' => true, 'targetClass' => Competition::className(), 'targetAttribute' => ['competition_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'competition_id' => Yii::t('app', 'Competition ID'),
            'name' => Yii::t('app', 'Name'),
            'url' => Yii::t('app', 'Url'),
            'position' => Yii::t('app', 'Position'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompetition()
    {
        return $this->hasOne(\common\models\Competition::className(), ['id' => 'competition_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompetitionWinners()
    {
        return $this->hasMany(\common\models\CompetitionWinner::className(), ['prize_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(\common\models\CompetitionUser::className(), ['id' => 'user_id'])->viaTable('competition_winner', ['prize_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\CompetitionPrizeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\CompetitionPrizeQuery(get_called_class());
    }


}
