<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "competition_winner".
 *
 * @property integer $prize_id
 * @property integer $user_id
 * @property string $date
 *
 * @property \common\models\CompetitionPrize $prize
 * @property \common\models\CompetitionUser $user
 * @property string $aliasModel
 */
abstract class CompetitionWinner extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'competition_winner';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['prize_id', 'user_id'], 'required'],
            [['prize_id', 'user_id'], 'integer'],
            [['date'], 'safe'],
            [['prize_id'], 'exist', 'skipOnError' => true, 'targetClass' => CompetitionPrize::className(), 'targetAttribute' => ['prize_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => CompetitionUser::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'prize_id' => Yii::t('app', 'Prize ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'date' => Yii::t('app', 'Date'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPrize()
    {
        return $this->hasOne(\common\models\CompetitionPrize::className(), ['id' => 'prize_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\CompetitionUser::className(), ['id' => 'user_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\CompetitionWinnerQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\CompetitionWinnerQuery(get_called_class());
    }


}
