<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "pay_log".
 *
 * @property integer $id
 * @property string $date
 * @property string $data
 * @property string $aliasModel
 */
abstract class PayLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pay_log';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date'], 'required'],
            [['date'], 'safe'],
            [['data'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'date' => Yii::t('app', 'Date'),
            'data' => Yii::t('app', 'Data'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\PayLogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\PayLogQuery(get_called_class());
    }


}
