<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Apply Time' => '',
    'Auth Key' => '',
    'Competition ID' => 'Конкурс',
    'Country ID' => 'Страна',
    'Created At' => '',
    'Created Date' => '',
    'Date' => 'Дата',
    'Description' => 'Описание',
    'Email' => '',
    'Extension' => '',
    'Full Name' => 'Имя',
    'ID' => '',
    'Is Social' => '',
    'Name' => 'Название',
    'No' => 'Нет',
    'Open' => '',
    'Organizer' => 'Организатор',
    'Organizer Url' => 'Ссылка на сайт, группу или страницу соц. сети',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Path' => '',
    'Photo File ID' => 'Фотография',
    'Position' => '',
    'Prize ID' => 'Приз',
    'Slug' => '',
    'Social ID' => '',
    'Social Slug' => '',
    'Status' => '',
    'Status ID' => '',
    'Title' => '',
    'Updated At' => '',
    'Url' => 'Ссылка',
    'Url Protocol' => '',
    'User ID' => '',
    'Username' => 'Логин',
    'Version' => '',
    'Video Url' => 'Видео конкурса',
    'Vk ID' => '',
    'Yes' => 'Да',
    'You are not allowed to {0} record #{1}' => '',
];
